#!/usr/bin/env python3
"""Build the dataset for the browser explorer (web/) from the committed dump. No database connection needed.

  webexport.py [--out web/crates/app/public/data]   write the dataset
  webexport.py --check                               build in memory and compare with what is on disk

The browser runs SurrealDB 3.3 in memory (WebAssembly) and loads this on every visit, so the dataset is shaped for
load speed (see web/README.md):
- **schema.surql:** the tables, analyzers and COMPUTED fields only. Tables are SCHEMALESS, since the data was
  validated on the way in, and their permissions are `select` only: visitors query as a guest, so every write is a
  no-op.
- **tables/<table>.surql:** one file per table of `INSERT` statements, in load order: vocabularies and entities,
  then claims, then relations. Fields the explorer doesn't need are dropped: `prov`, `created_at`, `updated_at`,
  and `ext._*` import hashes.
- **indexes.surql:** every index, built after the data (much faster than indexing row by row).
- **functions.surql:** the `fn::` query library (from web/kb/functions.surql).
- **schema.json:** tables, fields, types and comments, for the schema browser and autocomplete (visitors can't
  run `INFO FOR DB`).
- **gallery.json:** example queries (db/queries.md plus web/kb/gallery.surql).
- **manifest.json:** the file list with sizes and hashes, row counts, and the dataset version.

The private archive tables (`snapshot`, `revision`) and `migration` are left out.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DUMP = REPO / "db" / "dump"
SCHEMA = REPO / "db" / "schema"
WEBKB = REPO / "web" / "kb"
OUT = REPO / "web" / "crates" / "app" / "public" / "data"

EXCLUDE = {"snapshot", "revision", "migration"}
ORDER = ["kind", "era", "topic", "unit", "metric", "actor", "place", "event", "system", "work", "source", "term",
         "media", "claim", "observation", "passage", "question", "design_note"]
DROP_FIELDS = {"prov", "created_at", "updated_at"}
CHUNK = 500
SAFE_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


# --- SurrealQL literals from the dump's tagged JSON ----------------------------------------------------------------

def s_str(x: str) -> str:
    return '"' + (x.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")
                  .replace("\t", "\\t")) + '"'


def s_key(k) -> str:
    if isinstance(k, str):
        return k if SAFE_KEY.match(k) else "⟨" + k.replace("⟩", "\\⟩") + "⟩"
    if isinstance(k, list):
        return "[" + ",".join(lit(x) for x in k) + "]"
    return str(k)


def lit(v) -> str:
    if isinstance(v, dict):
        if "$rid" in v:
            t, k = v["$rid"]
            return f"{t}:{s_key(k)}"
        if "$dt" in v:
            return "d" + s_str(v["$dt"])
        if "$geo" in v:
            return lit(v["$geo"])           # a GeoJSON-shaped object literal is parsed as geometry
        if "$dec" in v:
            return v["$dec"] + "dec"
        return "{" + ",".join(f"{s_str(k)}:{lit(x)}" for k, x in v.items()) + "}"
    if isinstance(v, list):
        return "[" + ",".join(lit(x) for x in v) + "]"
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "NULL"
    if isinstance(v, str):
        return s_str(v)
    if isinstance(v, float):
        r = repr(v)
        return r if ("." in r or "e" in r or "inf" in r or "nan" in r) else r + ".0"
    return str(v)


def slim(row: dict) -> dict:
    out = {k: v for k, v in row.items() if k not in DROP_FIELDS}
    if isinstance(out.get("ext"), dict):
        out["ext"] = {k: v for k, v in out["ext"].items() if not k.startswith("_")}
    return out


# --- schema --------------------------------------------------------------------------------------------------------

def schema_text() -> str:
    parts = []
    for f in sorted(SCHEMA.glob("[0-9][0-9][0-9][0-9]_*.surql")):
        if f.name.startswith("0006_"):          # audit events: the browser copy is read-only
            continue
        parts.append(f.read_text())
    return "\n".join(parts)


def strip_comments(text: str) -> str:
    text = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("--"))
    return re.sub(r"\s+COMMENT\s+\"(?:[^\"\\]|\\.)*\"", "", text)


def statements(text: str, prefix: str) -> list[str]:
    return [m.group(0).strip() for m in re.finditer(rf"{prefix}[^;]*;", strip_comments(text))]


def web_schema(text: str, tables: list[str]) -> str:
    out = ["-- Generated by db/tools/webexport.py from db/schema/ (loose, read-only copy for the browser).", ""]
    out += statements(text, r"DEFINE ANALYZER")
    for st in statements(text, r"DEFINE TABLE"):
        name = re.match(r"DEFINE TABLE (?:IF NOT EXISTS )?(\w+)", st).group(1)
        if name in EXCLUDE:
            continue
        st = re.sub(r"\s+CHANGEFEED \d+d( INCLUDE ORIGINAL)?", "", st)
        st = re.sub(r"\s+ENFORCED", "", st)
        st = st.replace("SCHEMAFULL", "SCHEMALESS").rstrip(";") + " PERMISSIONS FOR select FULL;"
        out.append(st)
    for st in statements(text, r"DEFINE FIELD"):
        if " COMPUTED " in st and re.search(r" ON (\w+) ", st).group(1) not in EXCLUDE:
            out.append(st)
    return "\n".join(out) + "\n"


def web_indexes(text: str) -> str:
    out = ["-- Generated by db/tools/webexport.py: every index, built after the data is loaded."]
    for st in statements(text, r"DEFINE INDEX"):
        if re.search(r" ON (\w+) ", st).group(1) not in EXCLUDE:
            out.append(st)
    return "\n".join(out) + "\n"


def schema_json(text: str) -> dict:
    """Tables and fields with their types and comments, parsed from the migrations (later definitions win)."""
    tables: dict[str, dict] = {}
    for m in re.finditer(r"DEFINE TABLE (?:IF NOT EXISTS |OVERWRITE )?(\w+)([^;]*);", text):
        name, rest = m.group(1), m.group(2)
        if name in EXCLUDE:
            continue
        c = re.search(r"COMMENT\s+\"((?:[^\"\\]|\\.)*)\"", rest)
        rel = re.search(r"TYPE RELATION IN ([\w| ]+?) OUT ([\w| ]+?)(?: ENFORCED| SCHEMA| CHANGEFEED|$)", rest)
        tables[name] = {"comment": c.group(1) if c else None, "fields": {},
                        "relation": {"in": rel.group(1).split(" | "), "out": rel.group(2).split(" | ")} if rel else None}
    for line in text.splitlines():
        m = re.match(r"\s*DEFINE FIELD (?:IF NOT EXISTS |OVERWRITE )?([\w.\[\]*]+)\s+ON (?:TABLE )?(\w+)\s*(.*?);\s*(?:--\s*(.*))?$", line)
        if not m or m.group(2) not in tables:
            continue
        field, table, rest, note = m.groups()
        typ = re.search(r"TYPE (.+?)(?: DEFAULT| VALUE| ASSERT| READONLY| REFERENCE| COMPUTED| INLINE| COMMENT|$)", rest)
        computed = re.search(r"COMPUTED (.+)$", rest)
        tables[table]["fields"][field] = {"type": typ.group(1).strip() if typ else ("computed" if computed else None),
                                          "computed": computed.group(1).strip() if computed else None,
                                          "note": note.strip() if note else None}
    return {"tables": tables, "functions": functions()}


def functions() -> list[dict]:
    """The fn:: library with each function's parameters and the comment line above it."""
    path = WEBKB / "functions.surql"
    if not path.exists():
        return []
    out = []
    for m in re.finditer(r"((?:^--[^\n]*\n)*)DEFINE FUNCTION (fn::\w+)\(([^)]*)\)", path.read_text(), flags=re.M):
        doc = " ".join(l[2:].strip() for l in m.group(1).splitlines()).strip()
        out.append({"name": m.group(2), "params": m.group(3).strip(), "doc": doc})
    return out


# --- gallery -------------------------------------------------------------------------------------------------------

def gallery() -> list[dict]:
    """Example queries: db/queries.md (## sections, ```surql blocks, `-- comment` titles) and web/kb/gallery.surql."""
    items = []

    def add_block(section: str, block: str):
        title, lines = None, []
        for line in block.strip().splitlines() + ["-- "]:
            if line.startswith("-- ") or line.strip() == "--":
                query = "\n".join(lines).strip()
                if query and not re.search(r"\b(" + "|".join(EXCLUDE) + r")\b", query):   # not shipped to the browser
                    t = title or section
                    items.append({"section": section, "title": t[:1].upper() + t[1:], "query": query})
                    lines, title = [], None
                if line.strip() not in ("--", "-- "):
                    title = line[3:].strip() if title is None else title + " " + line[3:].strip()
            else:
                lines.append(line)

    md = (REPO / "db" / "queries.md").read_text()
    section = "Examples"
    for part in re.split(r"(^## .*$)", md, flags=re.M):
        if part.startswith("## "):
            section = part[3:].strip()
            continue
        for block in re.findall(r"```surql\n(.*?)```", part, flags=re.S):
            add_block(section, block)
    extra = WEBKB / "gallery.surql"
    if extra.exists():
        section = "Explorer"
        for part in re.split(r"(^-- ## .*$)", extra.read_text(), flags=re.M):
            if part.startswith("-- ## "):
                section = part[6:].strip()
            elif part.strip():
                add_block(section, part)
    return items


# --- build ---------------------------------------------------------------------------------------------------------

def build() -> dict[str, bytes]:
    text = schema_text()
    files = {p.stem: p for p in DUMP.glob("*.jsonl") if p.stem not in EXCLUDE}
    relations = {t for t, p in files.items() if '"in":' in p.open().readline()}
    order = ([t for t in ORDER if t in files] + sorted(t for t in files if t not in ORDER and t not in relations)
             + sorted(relations))
    out: dict[str, bytes] = {}
    counts, tables = {}, []
    for t in order:
        rows = [slim(json.loads(l)) for l in files[t].read_text().splitlines() if l.strip()]
        stmts = [f"INSERT {'RELATION ' if t in relations else ''}INTO {t} [{','.join(lit(r) for r in rows[i:i + CHUNK])}];"
                 for i in range(0, len(rows), CHUNK)]
        out[f"tables/{t}.surql"] = ("\n".join(stmts) + "\n").encode()
        counts[t] = len(rows)
        tables.append(t)
    out["schema.surql"] = web_schema(text, tables).encode()
    out["indexes.surql"] = web_indexes(text).encode()
    fn = WEBKB / "functions.surql"
    out["functions.surql"] = fn.read_bytes() if fn.exists() else b""
    out["schema.json"] = json.dumps(schema_json(text), ensure_ascii=False, indent=1, sort_keys=True).encode()
    out["gallery.json"] = json.dumps(gallery(), ensure_ascii=False, indent=1).encode()
    entries = [{"path": p, "bytes": len(b), "sha256": hashlib.sha256(b).hexdigest()} for p, b in sorted(out.items())]
    version = hashlib.sha256("".join(e["sha256"] for e in entries).encode()).hexdigest()[:16]
    manifest = {"format": 1, "version": version, "engine": "surrealdb 3.3",
                "load": ["schema.surql", *[f"tables/{t}.surql" for t in tables], "indexes.surql", "functions.surql"],
                "files": entries, "counts": counts,
                "attribution": "Place geometry: ODbL 1.0, © OpenStreetMap contributors."}
    out["manifest.json"] = json.dumps(manifest, ensure_ascii=False, indent=1).encode()
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true", help="compare with the files on disk; write nothing")
    a = ap.parse_args()
    built = build()
    if a.check:
        stale = [p for p, b in built.items() if not (a.out / p).exists() or (a.out / p).read_bytes() != b]
        extra = [str(p.relative_to(a.out)) for p in a.out.rglob("*") if p.is_file()
                 and str(p.relative_to(a.out)) not in built] if a.out.exists() else []
        for p in stale:
            print("stale", p)
        for p in extra:
            print("extra", p)
        print("OK" if not stale and not extra else f"{len(stale)} stale, {len(extra)} extra")
        return 1 if stale or extra else 0
    for p, b in built.items():
        dest = a.out / p
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.exists() or dest.read_bytes() != b:
            dest.write_bytes(b)
    for p in a.out.rglob("*"):
        if p.is_file() and str(p.relative_to(a.out)) not in built:
            p.unlink()
    m = json.loads(built["manifest.json"])
    total = sum(e["bytes"] for e in m["files"])
    print(f"dataset {m['version']}: {sum(m['counts'].values())} rows in {len(m['counts'])} tables, "
          f"{total / 1e6:.1f} MB -> {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
